#!/bin/sh
#
# Init script for dync-server
#
# chkconfig:   - 30 70
# description: Redirects incoming files to target openBis dropbox

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/dync-server"
prog="dyncserver"
config="/etc/dync_server.conf"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog
pidfile=/var/run/${prog}.pid

start() {
    echo -n $"Starting $prog: "
    [ -x $exec ] || return 5
    [ -f $config ] || return 6
    if [ -f $lockfile ] ; then
	    if [ -f $pidfile ] ; then
		    return 0
	    else
		    echo "lockfile exists, but pidfile does not."
		    return 1
	    fi
    fi
    [ -f $lockfile ] && return 0
    # USER and USER_CONFIG_FILE must be defined in config
    . $config
    if [ ! -n "$USER" ] ; then
	    echo "missing value USER in config file $config"
	    return 6
    fi
    su $USER -c "dync-server -d start"
    retval=$?
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    [ -f $pidfile ] || return 1
    read pid < $pidfile
    [ -n "$pid" ] || return 1

    su $USER -c "dync-server -d stop"
    retval=$?
    rm -f $lockfile
    if [ ! $retval -eq 0 ] ; then
        echo "dync-server with pid $pid could not be stopped."
        return 1
    fi
    return 0
}

restart() {
    stop
    start
}

reload() {
    restart
}

force_reload() {
    restart
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}


case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    reload)
        rh_status_q || exit 7
        $1
        ;;
    force-reload)
        force_reload
        ;;
    status)
        rh_status
        ;;
    condrestart|try-restart)
        rh_status_q || exit 0
        restart
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|try-restart|reload|force-reload}"
        exit 2
esac
retcode=$?
[ $retcode -eq 0 ] && success || failure
echo
exit $retcode